version: '{branch}.{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: 
 - Win32
 - x64
environment:
  access_token:
    secure: 21m76jAVvcu7oACAHFnfCBltcwon+r5ZI3avfRmrNFAqJMn6RfLXwpBhPcJ617tD
  VCPKG_INSTALL_PATH: 'c:\tools\vcpkg\installed'
cache:
- C:\tools\vcpkg\installed -> vcpkg-packages.txt
install:
# Powershell block below is to install the c++ dependencies via vcpkg. The pseudo code is:
# 1. Check whether the vcpkg install directory exists (note that updating the vcpkg-packages.txt file
#    will cause the appveyor cache rules to invalidate the directory)
# 2. If the directory is missing:
#    a. Update the vcpkg source (including port files) and build the vcpkg binary,
#    b. Install the missing packages.
- ps: |
      $env:PACKAGES = Get-Content -Path vcpkg-packages.txt
      Write-Host "vcpkg list: $env:PACKAGES"
      if(!(Test-Path -Path ($env:VCPKG_INSTALL_PATH))) {
          cd c:\tools\vcpkg
          $env:GIT_REDIRECT_STDERR = '2>&1' # git is writing non-errors to STDERR when doing git pull. Send to STDOUT instead.
          git pull origin master
          .\bootstrap-vcpkg.bat
          Add-Content "C:\tools\vcpkg\triplets\$env:PLATFORM-windows.cmake" "set(VCPKG_BUILD_TYPE release)"
          .\vcpkg install --triplet $env:PLATFORM-windows $env:PACKAGES.split()
          cd "$env:APPVEYOR_BUILD_FOLDER"
      }
      else {
        Write-Host "required vcpkg packages already installed."
      }
      c:\tools\vcpkg\vcpkg integrate install
build:
  parallel: true
  project: SIPSorcery.Media\SIPSorceryMedia.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: quiet
after_build:
#- 7z a bitcoin-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\build_msvc\%platform%\%configuration%\*.exe
artifacts:
- path: /.*\.nupkg/
deploy:
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: MMAD8YSvIgFD6mUWB2tdEGzBNbyfW/9TeB+yN325nQ/nHJMLhv2hBYan1CU1O60z
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
      appveyor_repo_tag: true
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
