version: '{branch}.{build}'
skip_tags: true
image: Visual Studio 2019
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG_INSTALL_PATH: 'c:\tools\vcpkg\installed'
  access_token:
    secure: 21m76jAVvcu7oACAHFnfCBltcwon+r5ZI3avfRmrNFAqJMn6RfLXwpBhPcJ617tD
cache:
- C:\tools\vcpkg\installed # -> vcpkg-packages.txt
install:
# Powershell block below is to install the c++ dependencies via vcpkg.
- ps: |
      WRITE-HOST "vcpkg triplet $env:TRIPLET"
      $env:PACKAGES = Get-Content -Path vcpkg-packages.txt
      Write-Host "vcpkg list: $env:PACKAGES"
      if(True) {
      #if(!(Test-Path -Path ($env:VCPKG_INSTALL_PATH))) {
          Add-Content "C:\tools\vcpkg\triplets\$env:TRIPLET.cmake" "set(VCPKG_BUILD_TYPE release)"
          vcpkg install --triplet x86-windows openssl libvpx libsrtp
          Exit-AppveyorBuild;
          vcpkg install --triplet x64-windows openssl libvpx libsrtp
          Exit-AppveyorBuild;
          vcpkg install --triplet x86-windows ffmpeg
          Exit-AppveyorBuild;
          vcpkg install --triplet x64-windows ffmpeg
          Exit-AppveyorBuild;
      }
      else {
        Write-Host "required vcpkg packages already installed."
      }
      vcpkg integrate install
build_script:
- ps: |
      msbuild /m SIPSorceryMedia.sln /p:Configuration=Release /p:Platform=Win32 /t:clean,build
      msbuild /m SIPSorceryMedia.sln /p:Configuration=Release /p:Platform=x64 /t:clean,build
after_build:
#- 7z a bitcoin-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\build_msvc\%platform%\%configuration%\*.exe
- ps: |
       Write-Host "APPVEYOR_REPO_TAG=$env:APPVEYOR_REPO_TAG."
       nuget pack src\SIPSorcery.Media.nuspec
       dir src\*.nupkg
artifacts:
- path: 'src\*.nupkg'
deploy:
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: MMAD8YSvIgFD6mUWB2tdEGzBNbyfW/9TeB+yN325nQ/nHJMLhv2hBYan1CU1O60z
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: 'src\*.nupkg'
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
  - provider: GitHub
    artifact: 'src\*.nupkg'           # upload all NuGet packages to release assets
    draft: true
    prerelease: true
    auth_token:
      secure: E58r+OknoQn8+bsPRT6l3U2K4kfOpDiGCo1C75LkVg+R/RBHpY//J8UCXEfVvyRB
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
